### ISSUE TITLE
Fix Horizontal Scrollbar Responsive issue

### ISSUE THREAD

**Issue by fabdul88** [Sanket-Mathur/Bookstore-template#14]
**Describe the bug**
Horizontal scrollbar in Genres and Events section not visible on screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Developer tools, and set screen size to: **768px by 1937px**
2. On Genres and Events section, horizontal scrollbar is pushed out of view.

**Expected behavior**
Horizontal Scrollbar should be in view. This can be seen at screen size: **768px by 1322px**. This brings the horizontal scrollbar in view.

**Screenshots**
Here are screenshots for context:

Horizontal Scrollbar Out of view at **768px by 1937px**

![Scrollbar Out of View](https://user-images.githubusercontent.com/60126985/139915727-391d187d-76c2-424b-ab14-32c231ea0295.png)

Horizontal Scrollbar in view at  **768px by 1322px**

![Scrollbar in View](https://user-images.githubusercontent.com/60126985/139915769-64bedfb9-b651-4955-bb10-11e8bc97911e.png)

**.cards** pushing horizontal scrollbar out of view

![Section cards pushing scrollbar out](https://user-images.githubusercontent.com/60126985/139916093-aa3c90a7-a875-4a1c-940b-f219e2119358.png)

**.cards** shorter and displaying horizontal scrollbar

![Section cards smaller and scrollbar in view](https://user-images.githubusercontent.com/60126985/139916276-f3f18a3c-e575-4b6d-a027-7d102bee3b1c.png)

**Desktop (please complete the following information):**
 - Extended Screen Display Resolution 3840 x 2160
 - OS: Mac OS Monterey
 - Browser chrome

**Smartphone (please complete the following information):**
**N/A**

**Additional context**
For additional context, refer to *code review* issue #13

**Comment by Sanket-Mathur** [comment]
Thank you very much for pointing it out. I rarely test my designs for such extreme screen sizes.

It looks even worse in the range 1400px-1525px vertically when the scrollbar is only partly visible.
The scrollbar is not considered under the content of the block and that's why not assigned any space by flex. This should be an easy fix by adding a small bottom padding to the event and genres section.

However, there would be some similar issues to fix related to content not being properly visible for very small screen sizes as well. I'll create a pull request after fixing all such issues.

**Comment by fabdul88** [comment]
Yes, 4k resolutions are pretty standard, thus having a responsive design that accommodates users within this category keeps the UI consistent. 

Since a user might have other programs open that would take up screen real estate, a narrowed down browser window would still be able to display the correct UI on a 4k screen.

Adding padding is a great fix! Another alternative to prevent the scrollbar from moving out of view would be to prevent the .cards container extending vertically, by using an absolute unit, along with a "min value" for smaller screen sizes.

Overall, great work Sanket
