### ISSUE TITLE
Make the template responsive to difference device size

### ISSUE THREAD

**Issue by Sanket-Mathur** [Sanket-Mathur/Bookstore-template#2]
The website is only compatible with large devices. It must be formatted in order to be correctly displayed in all device sizes.
The design might have to be changed slightly for different devices.

**Comment by anupriyalathey** [comment]
I would like to do this. Please assign it to me. Thank you

**Comment by Sanket-Mathur** [comment]
@fabdul88 I've fixed the issue that you referenced in the above PR. Would highly appreciate your reviews to the changes made.
