### ISSUE TITLE
Change email and mobile number to links

### ISSUE THREAD

**Issue by Sanket-Mathur** [Sanket-Mathur/Bookstore-template#5]
The email and mobile number in the end section must be converted to links using mailto and tel
The website should remain the same from the design aspect other than the email and mobile number having a pointer cursor.

![Screenshot 2021-10-14 at 03-33-47 Lighthouse Hammock](https://user-images.githubusercontent.com/52062536/137219000-34e76ea4-5805-447f-bbd0-fed2c6ccdb9a.png)

**Comment by YuriCodes** [comment]
Hello, i'd like to work on this !

**Comment by Sanket-Mathur** [comment]
Best of luck @YuriCodes

**Comment by YuriCodes** [comment]
Thank you! I already worked on it, It's on PR #9 : )
